"""Ticker universes. Current constituents => survivorship bias; fine for a trial, not for claims."""

SP100 = """AAPL ABBV ABT ACN ADBE AIG AMD AMGN AMT AMZN AVGO AXP BA BAC BK BKNG BLK BMY BRK-B C
CAT CHTR CL CMCSA COF COP COST CRM CSCO CVS CVX DE DHR DIS DUK EMR F FDX GD GE GILD GM GOOG
GOOGL GS HD HON IBM INTC INTU ISRG JNJ JPM KO LIN LLY LMT LOW MA MCD MDLZ MDT MET META MMM MO
MRK MS MSFT NEE NFLX NKE NVDA ORCL PEP PFE PG PM QCOM RTX SBUX SCHW SO SPG T TGT TMO TMUS TXN
UNH UNP UPS USB V VZ WFC WMT XOM""".split()

UNIVERSES = {"sp100": SP100}
